#!/usr/bin/env bash
# Bash script that displays infinity and beyond indefinitely  With a sleep 2 in between each iteration and echo I am invincible!!! when receiving a SIGTERM signal
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'I am invincible!!!'" SIGTERM
done